driver:
    resource: "@DriverBundle/Controller/"
    type:     annotation
    prefix:   /motorista

client:
    resource: "@ClientBundle/Controller/"
    type:     annotation
    prefix:   /cliente

site:
    resource: "@SiteBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"