<?php

namespace AdminBundle\Repository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAddressByUser($user_id)
    {   
    

        return $this->createQueryBuilder('address')
            ->where('address.user_id', $user_id)
            ->orderBy('address.name', 'ASC');
    }
}
