<?php

namespace AdminBundle\Repository;

/**
 * NeighborhoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeighborhoodRepository extends \Doctrine\ORM\EntityRepository
{
    public function createAlphabeticalQueryBuilder()
    {
        return $this->createQueryBuilder('point')
            ->orderBy('point.name', 'ASC');
    }
}
