<?php

namespace AdminBundle\Repository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCount($email)
    {
        $qb = $this->createQueryBuilder('n')
        ->where('n.email = :email')
        ->setParameter('email', $email);

        $query = $qb->getQuery();
        $totalrows = $query->getResult();

        return count($totalrows);
        
    }

}
