<?php

namespace AdminBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function createAlphabeticalQueryBuilderDrivers()
    {
        return $this->createQueryBuilder('fos_user')
            ->orderBy('fos_user.name', 'ASC');
    }

    public function findOneByEmail($email)
    {

        var_dump($email);die;

        $qb = $this->createQueryBuilder('n')
        ->where('n.email = :email')
        ->setParameter('email', $email);

        $query = $qb->getQuery();
        $totalrows = $query->getResult();

        return count($totalrows);
        
    }
}
