<?php

namespace AdminBundle\Repository;

/**
 * WayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WayRepository extends \Doctrine\ORM\EntityRepository
{
}
